language: node_js
node_js:
  - lts/*
cache: npm install
addons:
  sonarqube: true
jobs:
  include:
    - stage: test
      script:
        - npm ci
        - npm run lint
        - npm run test
    - stage: deploy
      if: branch = master AND type != pull_request
      script:
        - printf -- "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}";
        - if [ "${TRAVIS_BRANCH}" = "master" ] && ! [ `printf -- "${TRAVIS_COMMIT_MESSAGE}" | grep "Publish"` ]; then
            git checkout ${TRAVIS_BRANCH};
            git reset --hard ${TRAVIS_COMMIT};
            git remote set-url origin ${CIVAR_GH_REPOSITORY_URL};
            npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}";
            if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
              if [ -z "${TRAVIS_COMMIT_MESSAGE##*"[major release]"*}" ]; then
                LERNA_CD_VERSION='major';
              elif [ -z "${TRAVIS_COMMIT_MESSAGE##*"[minor release]"*}" ]; then
                LERNA_CD_VERSION='minor';
              else
                LERNA_CD_VERSION='patch';
              fi;
              lerna publish --yes --cd-version ${LERNA_CD_VERSION};
            fi;
          fi;
stages:
  - test
  - deploy